@WebApi_HostAddress = http://localhost:5190

GET {{WebApi_HostAddress}}/
Accept: application/json

###

GET {{WebApi_HostAddress}}/resolutions
Accept: application/json

###

GET {{WebApi_HostAddress}}/resolutions/1
Accept: application/json